#ifndef __DSB_UTILS_H__
#define __DSB_UTILS_H__

#define DSB_MOVE      "    MOVE          "
#define DSB_LOAD_OA   "    LOAD-OA       "
#define DSB_LOAD_H_OA "    LOAD-W2S0-OA  "
#define DSB_LOAD_C_OA "    LOAD-W1S0-OA  "
#define DSB_LOAD_OB   "    LOAD-OB       "
#define DSB_LOAD_H_OB "    LOAD-W2S0-OB  "
#define DSB_LOAD_C_OB "    LOAD-W1S0-OB  "
#define DSB_STOR_OA   "    STOR-OA       "
#define DSB_STOR_H_OA "    STOR-W2S0-OA  "
#define DSB_STOR_C_OA "    STOR-W1S0-OA  "
#define DSB_ADD       "    ADD           "
#define DSB_SUB       "    SUB           "
#define DSB_BSLT      "    BSLT          "
#define DSB_BSLC      "    BSLC          "
#define DSB_BSRT      "    BSRT          "
#define DSB_AND       "    AND           "
#define DSB_OR        "    OR            "
#define DSB_XOR       "    XOR           "
#define DSB_NOT       "    NOT           "
#define DSB_COMP      "    COMP          "
#define DSB_BRAL      "    BRAL          "
#define DSB_BREQ      "    BREQ          "
#define DSB_BRNE      "    BRNE          "
#define DSB_BRHI      "    BRHI          "
#define DSB_BRHS      "    BRHS          "
#define DSB_BRLS      "    BRLS          "
#define DSB_BRLO      "    BRLO          "
#define DSB_BRGT      "    BRGT          "
#define DSB_BRGE      "    BRGE          "
#define DSB_BRLE      "    BRLE          "
#define DSB_BRLT      "    BRLT          "
#define DSB_BRMI      "    BRMI          "
#define DSB_RETURN    "    RETURN\n"

#endif //__DSB_UTILS_H__
